//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlientMoon.SharedKernel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlientMoon.SharedKernel.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; is not a valid credit card number..
        /// </summary>
        public static string CreditCardValidator {
            get {
                return ResourceManager.GetString("CreditCardValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; is not a valid email address..
        /// </summary>
        public static string EmailValidator {
            get {
                return ResourceManager.GetString("EmailValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be empty..
        /// </summary>
        public static string EmptyValidator {
            get {
                return ResourceManager.GetString("EmptyValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; has a name which does not exist in the enum..
        /// </summary>
        public static string EnumNameValidator {
            get {
                return ResourceManager.GetString("EnumNameValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; has a range of values which does not include the value provided..
        /// </summary>
        public static string EnumValidator {
            get {
                return ResourceManager.GetString("EnumValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be equal to &apos;{ComparisonValue}&apos;..
        /// </summary>
        public static string EqualValidator {
            get {
                return ResourceManager.GetString("EqualValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict occurred..
        /// </summary>
        public static string ErrorType_Conflict {
            get {
                return ResourceManager.GetString("ErrorType.Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation conflicts with existing data in the system..
        /// </summary>
        public static string ErrorType_ConflictDetail {
            get {
                return ResourceManager.GetString("ErrorType.ConflictDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Provider Error..
        /// </summary>
        public static string ErrorType_ExternalProvider {
            get {
                return ResourceManager.GetString("ErrorType.ExternalProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred with the external service provider required to process the request..
        /// </summary>
        public static string ErrorType_ExternalProviderDetail {
            get {
                return ResourceManager.GetString("ErrorType.ExternalProviderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed..
        /// </summary>
        public static string ErrorType_Failure {
            get {
                return ResourceManager.GetString("ErrorType.Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested operation could not be completed. Please try again later..
        /// </summary>
        public static string ErrorType_FailureDetail {
            get {
                return ResourceManager.GetString("ErrorType.FailureDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden..
        /// </summary>
        public static string ErrorType_Forbidden {
            get {
                return ResourceManager.GetString("ErrorType.Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the necessary permissions to perform this operation..
        /// </summary>
        public static string ErrorType_ForbiddenDetail {
            get {
                return ResourceManager.GetString("ErrorType.ForbiddenDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request provided..
        /// </summary>
        public static string ErrorType_InvalidRequest {
            get {
                return ResourceManager.GetString("ErrorType.InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request format or data is invalid..
        /// </summary>
        public static string ErrorType_InvalidRequestDetail {
            get {
                return ResourceManager.GetString("ErrorType.InvalidRequestDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid State..
        /// </summary>
        public static string ErrorType_InvalidState {
            get {
                return ResourceManager.GetString("ErrorType.InvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current state does not allow this operation to be performed..
        /// </summary>
        public static string ErrorType_InvalidStateDetail {
            get {
                return ResourceManager.GetString("ErrorType.InvalidStateDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Exceeded..
        /// </summary>
        public static string ErrorType_LimitExceeded {
            get {
                return ResourceManager.GetString("ErrorType.LimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum limit allowed for this operation has been exceeded..
        /// </summary>
        public static string ErrorType_LimitExceededDetail {
            get {
                return ResourceManager.GetString("ErrorType.LimitExceededDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found..
        /// </summary>
        public static string ErrorType_NotFound {
            get {
                return ResourceManager.GetString("ErrorType.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource or data does not exist in the system..
        /// </summary>
        public static string ErrorType_NotFoundDetail {
            get {
                return ResourceManager.GetString("ErrorType.NotFoundDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A system error occurred..
        /// </summary>
        public static string ErrorType_Problem {
            get {
                return ResourceManager.GetString("ErrorType.Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected problem occurred during the execution of the request..
        /// </summary>
        public static string ErrorType_ProblemDetail {
            get {
                return ResourceManager.GetString("ErrorType.ProblemDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error..
        /// </summary>
        public static string ErrorType_Server {
            get {
                return ResourceManager.GetString("ErrorType.Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request could not be processed due to an internal server error. The issue has been logged..
        /// </summary>
        public static string ErrorType_ServerDetail {
            get {
                return ResourceManager.GetString("ErrorType.ServerDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied..
        /// </summary>
        public static string ErrorType_Unauthorized {
            get {
                return ResourceManager.GetString("ErrorType.Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be authenticated or have sufficient permissions to perform this operation..
        /// </summary>
        public static string ErrorType_UnauthorizedDetail {
            get {
                return ResourceManager.GetString("ErrorType.UnauthorizedDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Unavailable..
        /// </summary>
        public static string ErrorType_Unavailable {
            get {
                return ResourceManager.GetString("ErrorType.Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system is currently unavailable due to maintenance or overload. Please try again later..
        /// </summary>
        public static string ErrorType_UnavailableDetail {
            get {
                return ResourceManager.GetString("ErrorType.UnavailableDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string ErrorType_Unexpected {
            get {
                return ResourceManager.GetString("ErrorType.Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occurred. Please contact support..
        /// </summary>
        public static string ErrorType_UnexpectedDetail {
            get {
                return ResourceManager.GetString("ErrorType.UnexpectedDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error..
        /// </summary>
        public static string ErrorType_Validation {
            get {
                return ResourceManager.GetString("ErrorType.Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be between {From} and {To} (exclusive)..
        /// </summary>
        public static string ExclusiveBetweenValidator {
            get {
                return ResourceManager.GetString("ExclusiveBetweenValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be greater than or equal to {ComparisonValue}..
        /// </summary>
        public static string GreaterThanOrEqualValidator {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be greater than {ComparisonValue}..
        /// </summary>
        public static string GreaterThanValidator {
            get {
                return ResourceManager.GetString("GreaterThanValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be between {From} and {To}..
        /// </summary>
        public static string InclusiveBetweenValidator {
            get {
                return ResourceManager.GetString("InclusiveBetweenValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address format is invalid..
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP must contain only digits..
        /// </summary>
        public static string InvalidOtpFormat {
            get {
                return ResourceManager.GetString("InvalidOtpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number format. (Example: +994501234567)..
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid state token format..
        /// </summary>
        public static string InvalidStateToken {
            get {
                return ResourceManager.GetString("InvalidStateToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be between {MinLength} and {MaxLength} characters..
        /// </summary>
        public static string LengthValidator {
            get {
                return ResourceManager.GetString("LengthValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be less than or equal to {ComparisonValue}..
        /// </summary>
        public static string LessThanOrEqualValidator {
            get {
                return ResourceManager.GetString("LessThanOrEqualValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be less than {ComparisonValue}..
        /// </summary>
        public static string LessThanValidator {
            get {
                return ResourceManager.GetString("LessThanValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login code: {0}..
        /// </summary>
        public static string Login_Otp_Message {
            get {
                return ResourceManager.GetString("Login.Otp.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be {MaxLength} characters or less..
        /// </summary>
        public static string MaxLengthValidator {
            get {
                return ResourceManager.GetString("MaxLengthValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be at least {MinLength} characters..
        /// </summary>
        public static string MinLengthValidator {
            get {
                return ResourceManager.GetString("MinLengthValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No additional information is available for this error. Please contact support..
        /// </summary>
        public static string NoFurtherDetails {
            get {
                return ResourceManager.GetString("NoFurtherDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; should not be empty..
        /// </summary>
        public static string NotEmptyValidator {
            get {
                return ResourceManager.GetString("NotEmptyValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; should not be equal to &apos;{ComparisonValue}&apos;..
        /// </summary>
        public static string NotEqualValidator {
            get {
                return ResourceManager.GetString("NotEqualValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; is required..
        /// </summary>
        public static string NotNullValidator {
            get {
                return ResourceManager.GetString("NotNullValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be null..
        /// </summary>
        public static string NullValidator {
            get {
                return ResourceManager.GetString("NullValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one special character (@, #, $, %, etc.)..
        /// </summary>
        public static string PasswordMustCharacter {
            get {
                return ResourceManager.GetString("PasswordMustCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one digit (0-9)..
        /// </summary>
        public static string PasswordMustDigit {
            get {
                return ResourceManager.GetString("PasswordMustDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lowercase letter (a-z)..
        /// </summary>
        public static string PasswordMustLower {
            get {
                return ResourceManager.GetString("PasswordMustLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter (A-Z)..
        /// </summary>
        public static string PasswordMustUpper {
            get {
                return ResourceManager.GetString("PasswordMustUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test_en.
        /// </summary>
        public static string PomodoroTime_NotEmpty {
            get {
                return ResourceManager.GetString("PomodoroTime.NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; may not be more than {ExpectedPrecision} digits in total, with allowance for {ExpectedScale} decimals..
        /// </summary>
        public static string PrecisionScaleValidator {
            get {
                return ResourceManager.GetString("PrecisionScaleValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified condition was not met for &apos;{PropertyName}&apos;..
        /// </summary>
        public static string PredicateValidator {
            get {
                return ResourceManager.GetString("PredicateValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registration confirmation code: {0}..
        /// </summary>
        public static string Register_Otp_Message {
            get {
                return ResourceManager.GetString("Register.Otp.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; is not in the correct format..
        /// </summary>
        public static string RegularExpressionValidator {
            get {
                return ResourceManager.GetString("RegularExpressionValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number or password is incorrect..
        /// </summary>
        public static string Users_CredentialsError {
            get {
                return ResourceManager.GetString("Users.CredentialsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided email address is already in use..
        /// </summary>
        public static string Users_EmailNotUnique {
            get {
                return ResourceManager.GetString("Users.EmailNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login session expired. Please log in again..
        /// </summary>
        public static string Users_LoginSessionExpired {
            get {
                return ResourceManager.GetString("Users.LoginSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested user could not be found..
        /// </summary>
        public static string Users_NotFound {
            get {
                return ResourceManager.GetString("Users.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phone number is already registered..
        /// </summary>
        public static string Users_PhoneNumberNotUnique {
            get {
                return ResourceManager.GetString("Users.PhoneNumberNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS requested too frequently. Please try again in a few moments..
        /// </summary>
        public static string Users_TooFrequentSmsRequest {
            get {
                return ResourceManager.GetString("Users.TooFrequentSmsRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many login attempts detected!.
        /// </summary>
        public static string Users_TooManyLoginAttempt {
            get {
                return ResourceManager.GetString("Users.TooManyLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many sign-up attempts. Please try again later..
        /// </summary>
        public static string Users_TooManySignUpAttempt {
            get {
                return ResourceManager.GetString("Users.TooManySignUpAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided OTP code is incorrect..
        /// </summary>
        public static string Users_VerifyOtpError {
            get {
                return ResourceManager.GetString("Users.VerifyOtpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation errors occurred..
        /// </summary>
        public static string Validation_General {
            get {
                return ResourceManager.GetString("Validation.General", resourceCulture);
            }
        }
    }
}
