<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<Compile Update="Resources\Messages.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Messages.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\Messages.az.resx">
			<DependentUpon>Messages.resx</DependentUpon>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Messages.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Messages.Designer.cs</LastGenOutput>
		</EmbeddedResource>

		<EmbeddedResource Update="Resources\Messages.ru.resx">
			<DependentUpon>Messages.resx</DependentUpon>
		</EmbeddedResource>
	</ItemGroup>
</Project>
