<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>disable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
		<PackageReference Include="Dapper" Version="2.1.66" />
		<PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.12">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.12">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0" />
		<PackageReference Include="NLog" Version="6.0.7" />
		<PackageReference Include="Oracle.EntityFrameworkCore" Version="8.21.121" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Core\SlientMoon.Application\SlientMoon.Application.csproj" />
		<ProjectReference Include="..\..\Shared\SlientMoon.SharedKernel\SlientMoon.SharedKernel.csproj" />
	</ItemGroup>
</Project>