// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SlientMoon.Infrastructure.Persistence.Contexts;

#nullable disable

namespace SlientMoon.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805154319_AddDescriptionToCourse")]
    partial class AddDescriptionToCourse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SlientMoon.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("LoginType")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RefreshTokenId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("RefreshTokenId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("CategoryTypeId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryTypeId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.CategoryType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("CategoryTypes", (string)null);
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("DurationSec")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Subtitle")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.CourseNarrator", b =>
                {
                    b.Property<string>("CourseId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("NarratorId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("CourseId", "NarratorId");

                    b.HasIndex("NarratorId");

                    b.ToTable("CourseNarrators");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.DailyThought", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("CourseId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("DailyThoughts");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.Favorite", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("CourseId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL AND \"CourseId\" IS NOT NULL");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.Narrator", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Gender")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Narrators");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Token")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.Reminder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DaysOfWeek")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reminders", (string)null);
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.Topic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ColorHex")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("IconKey")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Slug")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Title")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Topics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6f9b17f4-d55c-4f7f-a123-1d54bdf19001",
                            ColorHex = "#8E97FD",
                            CreatedAt = new DateTime(2026, 8, 5, 15, 43, 19, 566, DateTimeKind.Utc).AddTicks(5762),
                            IconKey = "leaf",
                            Slug = "reduce-stress",
                            Title = "Reduce Stress"
                        },
                        new
                        {
                            Id = "6f9b17f4-d55c-4f7f-a123-1d54bdf19002",
                            ColorHex = "#FFC97E",
                            CreatedAt = new DateTime(2026, 8, 5, 15, 43, 19, 566, DateTimeKind.Utc).AddTicks(5770),
                            IconKey = "moon",
                            Slug = "improve-sleep",
                            Title = "Improve Sleep"
                        });
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.Track", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CourseId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("DurationSec")
                        .HasColumnType("NUMBER(10)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MimeType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NarratorId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Title")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("NarratorId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.UserTopic", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("TopicId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("UserId", "TopicId");

                    b.HasIndex("TopicId");

                    b.ToTable("UserTopics", (string)null);
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("SlientMoon.Domain.Entities.RefreshToken", "RefreshToken")
                        .WithMany()
                        .HasForeignKey("RefreshTokenId");

                    b.Navigation("RefreshToken");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.Category", b =>
                {
                    b.HasOne("SlientMoon.Domain.Entities.CategoryType", "CategoryType")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoryType");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.Course", b =>
                {
                    b.HasOne("SlientMoon.Domain.Entities.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.CourseNarrator", b =>
                {
                    b.HasOne("SlientMoon.Domain.Entities.Course", "Course")
                        .WithMany("CourseNarrators")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlientMoon.Domain.Entities.Narrator", "Narrator")
                        .WithMany("CourseNarrators")
                        .HasForeignKey("NarratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Narrator");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.DailyThought", b =>
                {
                    b.HasOne("SlientMoon.Domain.Entities.Course", "Course")
                        .WithMany("DailyThoughts")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("SlientMoon.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SlientMoon.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.Reminder", b =>
                {
                    b.HasOne("SlientMoon.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.Track", b =>
                {
                    b.HasOne("SlientMoon.Domain.Entities.Course", "Course")
                        .WithMany("Tracks")
                        .HasForeignKey("CourseId");

                    b.HasOne("SlientMoon.Domain.Entities.Narrator", "Narrator")
                        .WithMany()
                        .HasForeignKey("NarratorId");

                    b.Navigation("Course");

                    b.Navigation("Narrator");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.UserTopic", b =>
                {
                    b.HasOne("SlientMoon.Domain.Entities.Topic", "Topic")
                        .WithMany("UserTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SlientMoon.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UserTopics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("UserTopics");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.CategoryType", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.Course", b =>
                {
                    b.Navigation("CourseNarrators");

                    b.Navigation("DailyThoughts");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.Narrator", b =>
                {
                    b.Navigation("CourseNarrators");
                });

            modelBuilder.Entity("SlientMoon.Domain.Entities.Topic", b =>
                {
                    b.Navigation("UserTopics");
                });
#pragma warning restore 612, 618
        }
    }
}
